### ISSUE TITLE
Last selected broadcast service seen when switching from one DASH service to another

### ISSUE THREAD

**Issue by nicholas-fr** [DVBproject/DVB-I-Reference-Client#1]
When switching from one DASH service to another DASH service, the last broadcast service selected is seen briefly. 
It would be ideal if A/V mute was applied instead of showing the last broadcast service.

The DVB-I client was running as a standard HbbTV application on an HbbTV 2.0.2 client.

As seen in this video: https://we.tl/t-fkTnlysHXB

**Comment by sofia-tsa** [comment]
I noticed it also but I've been mostly concentrating on the Operator Application side. The application tries to  hide the video using the BroadcastSupervisor object but obviously that isn't available in a normal HbbTV application. I'll change the implementation so that the broadcast is hidden using the normal HbbTV-API:s if the OperatorApp-extensions are not available.

**Comment by sofia-tsa** [comment]
Issue fixed
