### ISSUE TITLE
Aspect ratio wrong

### ISSUE THREAD

**Issue by haudiobe** [DVBproject/DVB-I-Reference-Client#33]
All,

I played the Hope stream on my Samsung Galaxy S20 and the aspect ratio is completely wrong.

Thanks

Thomas

**Comment by jpiesing** [comment]
On my Moto G5S plus (Android 8.1.0), the Hope stream started correct, then changed to have the wrong aspect ratio (compressed vertically with black bars added) and then changed back again.

This looks like a stream problem & hence we might want to remove Hope from the master service list.

**Comment by paulhiggs** [comment]
On my wide format Huawei Mate 10 Pro (1440x720) it starts correctly 
![2020-11-23 09 45 47](https://user-images.githubusercontent.com/3158807/99948356-40ffea80-2d71-11eb-893f-122c18238671.jpg)



but then the aspect ratio is messed up
![2020-11-23 09 45 54](https://user-images.githubusercontent.com/3158807/99948364-43fadb00-2d71-11eb-81e8-4ada316d7610.jpg)

This is not related to the DVB-I Reference Client, but possibly dash.js or the encoding/packaging itself, since the same issue occurs when playing https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html in https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html

**Comment by haudiobe** [comment]
Ok - maybe someone can file an issue here: https://github.com/Dash-Industry-Forum/dash.js/issues/new/choose

**Comment by haudiobe** [comment]
Done here https://github.com/Dash-Industry-Forum/dash.js/issues/3459

**Comment by dsilhavy** [comment]
This is an issue with the content. Chrome scales to dimensions: "2560x720" in dash.js and Shaka on the highest quality. There is only one init segment for all representations although they differ in sample aspect ratio and resolution. Might be worth checking

**Comment by paulhiggs** [comment]
Lets remove this service from our service list and close this issue
