### ISSUE TITLE
Provide service prominance

### ISSUE THREAD

**Issue by paulhiggs** [DVBProject/DVB-I-Reference-Client#85]
Example service list to contain different variants of prominance marking

- **Simple**: service is prominant - 'flag' of 'star'  to be shown again service name in channel list, channel change bar and EPG
- **Scaled**: service prominance is relative to other services - different colours to be used in the background of the service name when displayed in the channel list, channel change bar and EPG
- **Regional**: prominant in some regions - no service name highlighting to be shown if the region is nto matching
----
Use font and background colours to indicate services with different prominence
Announcement of a DVB-I Service List in a broadcast channel with a service name and service provider name.
* One font/background colour combination for use when @ranking is not provided
* Ten font/background colour combinations for use when @ranking has values 1 to 10 respectively
* One font/background colour combination for use when @ranking is between 11 and 100
* One font/background colour combination for use when @ranking is between 101 and 1000
* One font/background colour combination for use when @ranking is greater than 1001

**Comment by sofia-tsa** [comment]
I assume the last font/color combination should be applied for @ranking is greater than 1000

**Comment by sofia-tsa** [comment]
My engineer brain just interpreted the fourth last line as  > 1001 so there would not be any color/font combination applied to ranking value 1001. Or maybe it could say "equal or greater  than 1001". Anyway, it's just semantics, the idea is clear.

**Comment by sofia-tsa** [comment]
How to determine what country is selected for a Prominence-element that only has the country and ranking attributes? Using the selected regioId would be the simplest solution as the outermost Region element in the RegionList has the attribute countryCodes to determine the selected country. The problem is that the countryCodes attribute is a list of countrycodes so it may contain multiple countries and so there might be multiple Prominence elements that are valid. 

For now, I think I will implement the Prominence selection so that the first Prominence with a valid country for the region is selected.

**Comment by paulhiggs** [comment]
Each region must have a country code or country codes, so any of them that match a prominence element is OK.

**Comment by sofia-tsa** [comment]
Implemented in https://github.com/DVBProject/DVB-I-Reference-Client/releases/tag/2.28

**Comment by paulhiggs** [comment]
Reference Client sample implementation

![image](https://github.com/DVBProject/DVB-I-Reference-Client/assets/3158807/14bdad69-a67b-4663-b1db-d412b76f828f)
