### ISSUE TITLE
AccessibilityAttributes in Service Lists and Content Guide metadata

### ISSUE THREAD

**Issue by paulhiggs** [DVBProject/DVB-I-Reference-Client#93]
The commercial requirement for V&V of the Signalling of Applications for Accessibility Services states

>**Req 4.4-2           DVB-I metadata** 
DVB-I service list and content guide metadata shall be created to exercise all new signalling defined in order to meet the Reqs 4.2-1, 4.2-2 and 4.2-3. These streams shall include both service and event based signalling in order to meet Req 4.2-8.
Such metadata shall reference the test streams created on the basis of Req 4.3-1

Adding `<AccessibilityAttributes>` elements in various places should suffice. We don't include accessibility information in DVB DASH and there is no requirement for the reference app to interpret this new signalling.

**Comment by andreastai** [comment]
Thanks @jpiesing for the pointer!

@paulhiggs wrote:

> We don't include accessibility information in DVB DASH and there is no requirement for the reference app to interpret this new signalling.

To demonstrate the benefits of DVB-I for inclusion it would be important that the reference client uses the extended options to signal access services. An ideal use case would be the interaction between accessibility user preference and the selection of instances of a service. For this use case it would also be good to have accessibility services/metadata in DASH streams.

**Comment by paulhiggs** [comment]
`<AcessibilityAttributes>` are added to some of the services in the DVB-DASH reference service list - [backend/servicelists/TM-STREAM0075r1%20DVB-DASH_Reference_Streams.xml](https://raw.githubusercontent.com/DVBProject/DVB-I-Reference-Client/master/backend/servicelists/TM-STREAM0075r1%20DVB-DASH_Reference_Streams.xml)

**Comment by paulhiggs** [comment]
![image](https://github.com/DVBProject/DVB-I-Reference-Client/assets/3158807/c6db97ba-c89e-4298-a2f0-05c3f71413c5)

![image](https://github.com/DVBProject/DVB-I-Reference-Client/assets/3158807/ba6d7e35-5f78-4d0d-8a2e-d4a77de82996)

**Comment by paulhiggs** [comment]
AccessibilityAttributes are now included in Service Lists and Content Guide metadata and shown in the Reference Application

**Comment by andreastai** [comment]
@paulhiggs Thanks for adding the accessibility metadata in the reference client.

Some comments and observations:

* The heading Accessibility is not necessary and possibly also sometimes misleading because "Translation" subtitles are usually not seen as an access service.
* It would be better to write out the features in the detail view (e.g. "Subtitles, Spoken Subtitles, Audio Description...") rather than using icons. Icons maybe good in an overview view of the program. They are also not always recognized internationally.
* Information on languages should  be written out instead of using acronyms (e.g. "English" instead of "eng")
*  In international content services the subtitle purpose "translation" is usually not mentioned but the default (so just "English"). If it is for hard of hearing it is indicated as "English (hard of hearing).
* For the user the carriage and the format of the subtitles are not relevant. For demonstration purposes this may be interesting but for the general user it may be irritating. This also true for all other technical details of access services.
* I don't think that it is needed to signal to the user that a subtitle service can be used for text to speech. It is more important for the device if it can generated spoken subtitles from it (at least this my understanding)
* The closed caption icon is used for signing but belongs to subtitles.

**Comment by paulhiggs** [comment]
> Some comments and observations:
> 
> * The heading Accessibility is not necessary and possibly also sometimes misleading because "Translation" subtitles are usually not seen as an access service.
The translatable accessibility label is removed in commit [36c1909]
> * It would be better to write out the features in the detail view (e.g. "Subtitles, Spoken Subtitles, Audio Description...") rather than using icons. Icons maybe good in an overview view of the program. They are also not always recognized internationally.
> * Information on languages should  be written out instead of using acronyms (e.g. "English" instead of "eng")
Added in a few long form language names in commit [be1bd45]
> * In international content services the subtitle purpose "translation" is usually not mentioned but the default (so just "English"). If it is for hard of hearing it is indicated as "English (hard of hearing).
> * For the user the carriage and the format of the subtitles are not relevant. For demonstration purposes this may be interesting but for the general user it may be irritating. This also true for all other technical details of access services.
> * I don't think that it is needed to signal to the user that a subtitle service can be used for text to speech. It is more important for the device if it can generated spoken subtitles from it (at least this my understanding)
> * The closed caption icon is used for signing but belongs to subtitles.

**Comment by andreastai** [comment]
Thanks for addressing the comments @paulhiggs I will review asap.

**Comment by paulhiggs** [comment]
https://github.com/paulhiggs/DVB-I-Reference-Client/commits/bff1dc597f8663fe8194e47c4c30588d958792c2 removes AudioAttributes elements that are not included in clause 6.10.10 of A177, leaving only Coding, MixType and Language

**Comment by juhajoki** [comment]
@andreastai @paulhiggs can this be closed as done? see latest merged pull request https://github.com/DVBProject/DVB-I-Reference-Client/pull/109

**Comment by andreastai** [comment]
@juhajoki Thanks a lot for the reminder and apologies for the delay in reviewing the PR. I will check asap and come back with feedback in CW 50.

**Comment by paulhiggs** [comment]
Note that while the front end can make use of Accessibility Attributes and Service Prominence, the back end service list editor UI is unaware of these new elements and will remove them without warning.

**Comment by sofia-tsa** [comment]
Hi,

I added support for Prominence and ContentAttributes to the backend editor. For the ContentAttributes there is so much data that for now I decided to display the element as raw XML, it can be edited, and it won't be removed from the list if the editor is used but no an optimal solution.

Best regards,
Tomi

________________________________
Lähettäjä: Paul Higgs ***@***.***>
Lähetetty: keskiviikko 11. joulukuuta 2024 15.14
Vastaanottaja: DVBProject/DVB-I-Reference-Client ***@***.***>
Kopio: Tomi Sarparanta ***@***.***>; Assign ***@***.***>
Aihe: Re: [DVBProject/DVB-I-Reference-Client] AccessibilityAttributes in Service Lists and Content Guide metadata (Issue #93)


Note that while the front end can make use of Accessibility Attributes and Service Prominence, the back end service list editor UI is unaware of these new elements and will remove them without warning.

**Comment by juhajoki** [comment]
@paulhiggs @andreastai can you check whether this fulfills the requirement?

**Comment by andreastai** [comment]
Thanks @juhajoki @paulhiggs I reviewed the current status again (apologies for the delay). Thanks for addressing parts of my comments. From my view there still open issues, e.g.

> It would be better to write out the features in the detail view (e.g. "Subtitles, Spoken Subtitles, Audio Description...") rather than using icons. Icons maybe good in an overview view of the program. They are also not always recognized internationally.

> In international content services the subtitle purpose "translation" is usually not mentioned but the default (so just "English"). If it is for hard of hearing it is indicated as "English (hard of hearing).

> For the user the carriage and the format of the subtitles are not relevant. For demonstration purposes this may be interesting but for the general user it may be irritating. This also true for all other technical details of access services.

Furthermore only accessibility features that are available on the specific plattform should be shown (e.g. no HbbTV service on a HTML5 player).

I appreciate the work but right now from my view it has not the state to be used for demo purposes, e.g. I could not explain why some information is shown in the "accessibility section".

It may require a clearer concept or a wireframe to clarify what shoud be present. 

From my view we can leave this issue open because it has all the necessary history. I understand of course that there may not be a priority at the moment to work on this.

**Comment by paulhiggs** [comment]
Closing this issue. The reference app shows metadata use and is not intended to be the model for all applications.

New issues can be opened that identify specific aspects to change and can then have commits associated with them.
